// temp files in place to mimic getting files, will be replace with API getting files from nodes
export const staticFiles = [
  "Avengers.mp4",
  "Batman Begins.mp4",
  "Captain America.mp4",
  "Doctor Strange.mp4",
  "Endgame.mp4",
  "Frozen.mp4",
  "Guardians of the Galaxy.mp4",
  "Harry Potter.mp4",
  "Inception.mp4",
  "Jumanji.mp4",
  "Kung Fu Panda.mp4",
  "Lion King.mp4",
  "Mulan.mp4",
  "Narnia.mp4",
  "Oceans Eleven.mp4",
  "Pirates of the Caribbean.mp4",
  "Quantum of Solace.mp4",
  "Ratatouille.mp4",
  "Spiderman.mp4",
  "Titanic.mp4",
  "Up.mp4",
  "Venom.mp4",
  "Wonder Woman.mp4",
  "X-Men.mp4",
  "Yogi Bear.mp4",
  "Zootopia.mp4",
];
